version: "3"
services:
        db:
            container_name: customer_db
            image: postgres:10
            ports:
               - "5439:5432"
            volumes:
              - ./pgdata:/var/lib/postgresql/data/
            environment:
              POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
              POSTGRES_USER: ${POSTGRES_USER} 
              POSTGRES_DB: ${POSTGRES_DB}
            healthcheck:
              test: ["CMD-SHELL", "pg_isready"]
              interval: 15s
              timeout: 10s
              retries: 90
        app:
            container_name: customer_service
            build: ./app
            ports:
                - "8086:8080"
