version: "3.4"
services:
        db:
            container_name: customer_db
            build: ./db
            ports:
               - "${POSTGRES_HOST_PORT}:5432"
            environment:
              POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
              POSTGRES_USER: ${POSTGRES_USER} 
              POSTGRES_DB: ${POSTGRES_DB}
              SERVICE_DB: ${SERVICE_DB}
              SERVICE_USER: ${SERVICE_USER} 
              SERVICE_PASSWORD: ${SERVICE_PASSWORD} 
            healthcheck:
              test: ["CMD-SHELL", "pg_isready"]
              interval: 15s
              timeout: 10s
              retries: 90
        app:
            container_name: customer_service
            build: ./app
            ports:
                - "8086:8080"
            environment:
                    DATABASE_URI: postgresql://${SERVICE_USER}:${SERVICE_PASSWORD}@db:${POSTGRES_CONTAINER_PORT}/${SERVICE_DB} 
                    POSTGRES_PORT: ${POSTGRES_CONTAINER_PORT}
                    FLASK_APP: /code/customersvc/app.py
            depends_on:
             - db
